engines:
  pep8:
    enabled: true
  eslint:
    enabled: true
  csslint:
    enabled: true
  duplication:
    enabled: true
      config:
        languages:
        - javascript:
        - python:

ratings:
  paths:
  - testcube/**

exclude_paths:
- "**/tests/"
- "**/migrations/"
- "**/static/libs/"
- "**/static/docs/"
- "**/static/images/"
