engines:
  pep8:
    enabled: true
  eslint:
    enabled: true
  csslint:
    enabled: true
  duplication:
    enabled: true
    config:
      languages:
      - javascript:
      - python:

ratings:
  paths:
  - testcube/**

exclude_paths:
- "*.*"
- "docs/"
- "scripts/"
- "**/tests/"
- "**/migrations/"
- "testcube/static/libs/"
- "testcube/static/docs/"
- "testcube/static/images/"
